<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE paises [
 <!ELEMENT paises (pais*)>
 <!ELEMENT pais (nombre, unionEuropea*, otan*)>
 <!ELEMENT nombre (#PCDATA)>
 <!ELEMENT unionEuropea EMPTY>
 <!ELEMENT otan EMPTY>
]>
<paises>
    <pais>
        <nombre>España</nombre>
        <unionEuropea />
        <otan />
    </pais>
    <pais>
        <nombre>Noruega</nombre>
        <otan />
    </pais>
    <pais>
        <nombre>Austria</nombre>
        <unionEuropea />
    </pais>
</paises>